### PR TITLE
Added updated darwin support for Apple Silicon Macs and new Software Updates

### PR DESCRIPTION
**Pull request by Ishaanahuja7**
Updates `darwin_sigar.c` for latest macOS version support.

### CODE REVIEW

**Comment by Ishaanahuja7** [comment]
https://github.com/rapid7/mettle/pull/237

**Comment by Ishaanahuja7** [comment]
@busterb @timwr Please take a look at this for merging this PR to update it for Apple Silicon. Mettle for Apple Silicon wont build without these changes.

**Comment by usiegl00** [comment]
@Ishaanahuja7 Thank you! 
@jmartin-r7 Any update on this?

**Comment by space-r7** [comment]
Hi @Ishaanahuja7 and @usiegl00, sorry for the lack of movement on this so far! I'm starting to work on these this week, so I'm hoping we can at least get these sigar changes pulled into mettle. Currently working on setting this up and testing at the moment!

**Comment by Ishaanahuja7** [comment]
Any updates? @space-r7

**Review by timwr — APPROVED** [review]
Looks good to me

**Comment by space-r7** [comment]
Hey @Ishaanahuja7, I'm on research at the moment. I'll be able to return to this the first week of January. Sorry for the delay on this!

**Comment by busterb** [comment]
I can probably take a look at this in the meantime if you don't mind @space-r7, just got an M1 for this kind of thing.

**Comment by space-r7** [comment]
Not at all! Thanks, Brent!

**Comment by Ishaanahuja7** [comment]
Thats alright, no worries @space-r7. Thanks @busterb. Let me know if I can help with any testing. I already have an M1 Max.

**Comment by busterb** [comment]
```
oldimac:examples bcook$ ./sysinfo
name: macOS
version: 10.13.6
arch: x86
machine: x86_64
description: macOS High Sierra
patch_level: unknown
vendor: Apple
vendor_version: 10.13
vendor_name: macOS
vendor_code_name: High Sierra
vendor_uuid:
```

```
bcook@m1.lan:~/projects/hacking/mettle/eval/sigar (r7-custom *%) $ ./examples/sysinfo
name: macOS
version: 13.1.0
arch: arm64
machine: arm64
description: macOS Ventura
patch_level: unknown
vendor: Apple
vendor_version: 13.1
vendor_name: macOS
vendor_code_name: Ventura
vendor_uuid: 
```

**Comment by Ishaanahuja7** [comment]
@busterb Looks good to me. Can anybody merge this PR?

**Comment by timwr** [comment]
This should be merged now, but I'm not sure why github didn't automatically mark this pull request as merged.
Actually merging this pull request is more of a formality, the key thing would be to ensure that the changes here are added to the libsigar dependency here: https://github.com/rapid7/mettle/blob/master/deps/libsigar-1.6.3.tar.gz in https://github.com/rapid7/mettle/pull/237

**Comment by Ishaanahuja7** [comment]
@timwr Can you make a new tag and bump version to 1.6.5 so I can update the tar.gz in mettle?

**Comment by jmartin-tech** [comment]
This was landed to the wrong branch, I will rework commits and tag shortly.

**Comment by jmartin-tech** [comment]
@timwr sorry for the confusion here, we are using `r7-custom` as the release branch in this fork.

Merges have been sorted and new tag for 1.6.5 exists.

**Pull request merged**
